application: chess
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /rsc
  static_dir: rsc

- url: /.*
  script: chess_app.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
